//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DIUBDatabaseEntities : DbContext
    {
        public DIUBDatabaseEntities()
            : base("name=DIUBDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SemesterRecord> SemesterRecords { get; set; }
        public virtual DbSet<Tbl_Accounts1> Tbl_Accounts1 { get; set; }
        public virtual DbSet<Tbl_AttandanceFinal> Tbl_AttandanceFinal { get; set; }
        public virtual DbSet<Tbl_AttandanceMid> Tbl_AttandanceMid { get; set; }
        public virtual DbSet<Tbl_Book> Tbl_Book { get; set; }
        public virtual DbSet<Tbl_Borrow> Tbl_Borrow { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Department> Tbl_Department { get; set; }
        public virtual DbSet<Tbl_Employee1> Tbl_Employee1 { get; set; }
        public virtual DbSet<Tbl_Expense> Tbl_Expense { get; set; }
        public virtual DbSet<Tbl_Message> Tbl_Message { get; set; }
        public virtual DbSet<Tbl_MidResult> Tbl_MidResult { get; set; }
        public virtual DbSet<Tbl_Notes> Tbl_Notes { get; set; }
        public virtual DbSet<Tbl_Notices> Tbl_Notices { get; set; }
        public virtual DbSet<Tbl_PerSemesterRecord> Tbl_PerSemesterRecord { get; set; }
        public virtual DbSet<Tbl_PreEmployee> Tbl_PreEmployee { get; set; }
        public virtual DbSet<Tbl_PreSectionDistribution> Tbl_PreSectionDistribution { get; set; }
        public virtual DbSet<Tbl_PreStudent> Tbl_PreStudent { get; set; }
        public virtual DbSet<Tbl_PreSubjectDetails> Tbl_PreSubjectDetails { get; set; }
        public virtual DbSet<Tbl_PreTeacher> Tbl_PreTeacher { get; set; }
        public virtual DbSet<Tbl_Registration> Tbl_Registration { get; set; }
        public virtual DbSet<Tbl_Request> Tbl_Request { get; set; }
        public virtual DbSet<Tbl_SalaryCategory> Tbl_SalaryCategory { get; set; }
        public virtual DbSet<Tbl_SectionDistribution> Tbl_SectionDistribution { get; set; }
        public virtual DbSet<Tbl_Semester> Tbl_Semester { get; set; }
        public virtual DbSet<Tbl_SemesterCost> Tbl_SemesterCost { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
        public virtual DbSet<Tbl_SubjectDetails> Tbl_SubjectDetails { get; set; }
        public virtual DbSet<Tbl_Teacher1> Tbl_Teacher1 { get; set; }
    }
}
