//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MidResult
    {
        public int ResultID { get; set; }
        public string TeacherID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<double> AttandanceMid { get; set; }
        public Nullable<double> LabPerformanceMid { get; set; }
        public Nullable<double> QuizMid { get; set; }
        public Nullable<double> PerformanceMid { get; set; }
        public Nullable<double> MidFinal { get; set; }
        public Nullable<double> TotalMarksMid { get; set; }
        public string GradeMid { get; set; }
        public string Lab01 { get; set; }
        public string Lab02 { get; set; }
        public string Lab03 { get; set; }
        public string Lab04 { get; set; }
        public string LabMid { get; set; }
        public Nullable<double> AttendanceFinal { get; set; }
        public Nullable<double> QuizFinal { get; set; }
        public Nullable<double> PerformanceFinal { get; set; }
        public Nullable<double> LabPerformanceFinal { get; set; }
        public Nullable<double> FinalFinal { get; set; }
        public Nullable<double> TotalMarksFinal { get; set; }
        public string GradeFinal { get; set; }
        public Nullable<double> TotalMarks { get; set; }
        public string Grade { get; set; }
        public string LabFinal { get; set; }
        public Nullable<double> Quiz1 { get; set; }
        public Nullable<double> Quiz2 { get; set; }
        public Nullable<double> Quiz3 { get; set; }
        public Nullable<double> Quiz4 { get; set; }
        public Nullable<double> Quiz5 { get; set; }
        public Nullable<double> Quiz6 { get; set; }
    
        public virtual Tbl_SectionDistribution Tbl_SectionDistribution { get; set; }
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
        public virtual Tbl_SubjectDetails Tbl_SubjectDetails { get; set; }
        public virtual Tbl_Teacher1 Tbl_Teacher1 { get; set; }
    }
}
