//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Department()
        {
            this.Tbl_Employee1 = new HashSet<Tbl_Employee1>();
            this.Tbl_PreEmployee = new HashSet<Tbl_PreEmployee>();
            this.Tbl_PreSectionDistribution = new HashSet<Tbl_PreSectionDistribution>();
            this.Tbl_PreStudent = new HashSet<Tbl_PreStudent>();
            this.Tbl_PreSubjectDetails = new HashSet<Tbl_PreSubjectDetails>();
            this.Tbl_PreTeacher = new HashSet<Tbl_PreTeacher>();
            this.Tbl_SectionDistribution = new HashSet<Tbl_SectionDistribution>();
            this.Tbl_SubjectDetails = new HashSet<Tbl_SubjectDetails>();
            this.Tbl_Teacher11 = new HashSet<Tbl_Teacher1>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string TeacherID { get; set; }
    
        public virtual Tbl_Teacher1 Tbl_Teacher1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Employee1> Tbl_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreEmployee> Tbl_PreEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreSectionDistribution> Tbl_PreSectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreStudent> Tbl_PreStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreSubjectDetails> Tbl_PreSubjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreTeacher> Tbl_PreTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SectionDistribution> Tbl_SectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SubjectDetails> Tbl_SubjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Teacher1> Tbl_Teacher11 { get; set; }
    }
}
