//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Semester()
        {
            this.SemesterRecords = new HashSet<SemesterRecord>();
            this.Tbl_AttandanceFinal = new HashSet<Tbl_AttandanceFinal>();
            this.Tbl_AttandanceMid = new HashSet<Tbl_AttandanceMid>();
            this.Tbl_MidResult = new HashSet<Tbl_MidResult>();
            this.Tbl_PerSemesterRecord = new HashSet<Tbl_PerSemesterRecord>();
            this.Tbl_PreSectionDistribution = new HashSet<Tbl_PreSectionDistribution>();
            this.Tbl_Registration = new HashSet<Tbl_Registration>();
            this.Tbl_SectionDistribution = new HashSet<Tbl_SectionDistribution>();
            this.Tbl_SemesterCost = new HashSet<Tbl_SemesterCost>();
        }
    
        public int SemesterID { get; set; }
        public string SemesterName { get; set; }
        public string SemesterDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemesterRecord> SemesterRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceFinal> Tbl_AttandanceFinal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceMid> Tbl_AttandanceMid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MidResult> Tbl_MidResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PerSemesterRecord> Tbl_PerSemesterRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreSectionDistribution> Tbl_PreSectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Registration> Tbl_Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SectionDistribution> Tbl_SectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SemesterCost> Tbl_SemesterCost { get; set; }
    }
}
