//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Accounts1
    {
        public int AccountID { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    }
}
