//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PreSubjectDetails
    {
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string IsLabExist { get; set; }
    
        public virtual Tbl_Department Tbl_Department { get; set; }
    }
}
