//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SemesterCost
    {
        public int SemesterCostID { get; set; }
        public Nullable<int> SemesterIID { get; set; }
        public Nullable<int> CreditTaken { get; set; }
        public Nullable<decimal> AdmissionFee { get; set; }
        public Nullable<decimal> ComputerLab { get; set; }
        public Nullable<decimal> ScienceLab { get; set; }
        public Nullable<decimal> LanguageLab { get; set; }
        public Nullable<decimal> Studio { get; set; }
        public Nullable<decimal> Development { get; set; }
        public Nullable<decimal> Activity { get; set; }
        public Nullable<decimal> Miscellaneous { get; set; }
        public Nullable<decimal> PreviousDue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Due { get; set; }
        public string StudentID { get; set; }
    
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
    }
}
