//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Teacher1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Teacher1()
        {
            this.Tbl_AttandanceFinal = new HashSet<Tbl_AttandanceFinal>();
            this.Tbl_AttandanceMid = new HashSet<Tbl_AttandanceMid>();
            this.Tbl_Borrow = new HashSet<Tbl_Borrow>();
            this.Tbl_Department = new HashSet<Tbl_Department>();
            this.Tbl_MidResult = new HashSet<Tbl_MidResult>();
            this.Tbl_Notes = new HashSet<Tbl_Notes>();
            this.Tbl_Notices = new HashSet<Tbl_Notices>();
            this.Tbl_PreSectionDistribution = new HashSet<Tbl_PreSectionDistribution>();
            this.Tbl_Registration = new HashSet<Tbl_Registration>();
            this.Tbl_SectionDistribution = new HashSet<Tbl_SectionDistribution>();
        }
    
        public int ID { get; set; }
        public string TeacherID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string PermanentAddress { get; set; }
        public string PresentAddress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string MaritalStatus { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Password { get; set; }
        public string Type { get; set; }
        public string Picture { get; set; }
        public string DocumentsGiven { get; set; }
        public Nullable<int> SalaryCategoryID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceFinal> Tbl_AttandanceFinal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceMid> Tbl_AttandanceMid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Borrow> Tbl_Borrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Department> Tbl_Department { get; set; }
        public virtual Tbl_Department Tbl_Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MidResult> Tbl_MidResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notes> Tbl_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notices> Tbl_Notices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PreSectionDistribution> Tbl_PreSectionDistribution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Registration> Tbl_Registration { get; set; }
        public virtual Tbl_SalaryCategory Tbl_SalaryCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SectionDistribution> Tbl_SectionDistribution { get; set; }
    }
}
