//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SectionDistribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SectionDistribution()
        {
            this.Tbl_AttandanceFinal = new HashSet<Tbl_AttandanceFinal>();
            this.Tbl_AttandanceMid = new HashSet<Tbl_AttandanceMid>();
            this.Tbl_FinalResult = new HashSet<Tbl_FinalResult>();
            this.Tbl_LabResult = new HashSet<Tbl_LabResult>();
            this.Tbl_MidResult = new HashSet<Tbl_MidResult>();
            this.Tbl_Notes = new HashSet<Tbl_Notes>();
            this.Tbl_Notices = new HashSet<Tbl_Notices>();
            this.Tbl_Quiz = new HashSet<Tbl_Quiz>();
            this.Tbl_Registration = new HashSet<Tbl_Registration>();
            this.Tbl_TotalResult = new HashSet<Tbl_TotalResult>();
        }
    
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.TimeSpan> ClassStart { get; set; }
        public Nullable<System.TimeSpan> ClassEnd { get; set; }
        public string Day1 { get; set; }
        public string Day2 { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.TimeSpan> ClassStart2 { get; set; }
        public Nullable<System.TimeSpan> ClassEnd2 { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string Status { get; set; }
        public string TeacherID { get; set; }
        public string Room { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceFinal> Tbl_AttandanceFinal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AttandanceMid> Tbl_AttandanceMid { get; set; }
        public virtual Tbl_Department Tbl_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FinalResult> Tbl_FinalResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_LabResult> Tbl_LabResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MidResult> Tbl_MidResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notes> Tbl_Notes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Notices> Tbl_Notices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Quiz> Tbl_Quiz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Registration> Tbl_Registration { get; set; }
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_SubjectDetails Tbl_SubjectDetails { get; set; }
        public virtual Tbl_Teacher1 Tbl_Teacher1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TotalResult> Tbl_TotalResult { get; set; }
    }
}
