//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Quiz
    {
        public int QuizID { get; set; }
        public Nullable<double> Quiz1 { get; set; }
        public Nullable<double> Quiz2 { get; set; }
        public Nullable<double> Quiz3 { get; set; }
        public Nullable<double> QuizMid { get; set; }
        public Nullable<double> Quiz4 { get; set; }
        public Nullable<double> Quiz5 { get; set; }
        public Nullable<double> Quiz6 { get; set; }
        public Nullable<double> QuizFinal { get; set; }
        public string TeacherID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> SemesterID { get; set; }
    
        public virtual Tbl_SectionDistribution Tbl_SectionDistribution { get; set; }
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
        public virtual Tbl_SubjectDetails Tbl_SubjectDetails { get; set; }
        public virtual Tbl_Teacher1 Tbl_Teacher1 { get; set; }
    }
}
