//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Registration
    {
        public int RegID { get; set; }
        public string SubjectName { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.TimeSpan> ClassStart { get; set; }
        public Nullable<System.TimeSpan> ClassEnd { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Day1 { get; set; }
        public string Day2 { get; set; }
        public Nullable<System.TimeSpan> ClassStart2 { get; set; }
        public Nullable<System.TimeSpan> ClassEnd2 { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Credit { get; set; }
        public string TeacherID { get; set; }
        public string StudentID { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> SemesterID { get; set; }
    
        public virtual Tbl_SectionDistribution Tbl_SectionDistribution { get; set; }
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
        public virtual Tbl_Teacher1 Tbl_Teacher1 { get; set; }
    }
}
