//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PerSemesterRecord
    {
        public int SemesterRecordID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<double> CGPA { get; set; }
        public string StudentID { get; set; }
    
        public virtual Tbl_Semester Tbl_Semester { get; set; }
        public virtual Tbl_Student Tbl_Student { get; set; }
    }
}
